#!/bin/sh

mkdir -p $HOME/.local/src &&
cd $HOME/.local/src &&
git clone https://github.com/martanne/abduco &&
cd abduco &&
sudo make clean install &&
cd .. &&
git clone https://github.com/rpmohn/a4 &&
cd a4 &&
make && sudo make install &&
mkdir -p $HOME/.config/a4 &&
curl "https://raw.githubusercontent.com/Iodize13/a4-setup-script/main/a4.ini" > $HOME/.config/a4/a4.ini &&
https://raw.githubusercontent.com/Iodize13/a4-setup-script/main/setup
echo "alias a4='abduco -A my-session a4'" >> $HOME/.bashrc &&
abduco -A my-session a4
